# -*- coding: utf-8 -*-
"""SPY — IBS MEAN REVERSION STRATEGY

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cE9kmeN5cTFHu9pt_z4b3wNWDcZKTY7y
"""

"""
================================================================================
 SPY — IBS MEAN REVERSION STRATEGY (STANDALONE, WINNING PARAMETERS)
================================================================================
 Rules:
   ENTRY : Buy at next day's close-to-close return when today's IBS < 0.20
   EXIT  : Sell (go to cash) at next day's close-to-close return when
           today's IBS > 0.80

 IBS (Internal Bar Strength) = (Close - Low) / (High - Low)
   -> Close near the LOW of the day  => IBS near 0  => oversold  => BUY
   -> Close near the HIGH of the day => IBS near 1  => overbought => SELL

 DATA INTEGRITY:
   - yfinance auto_adjust=True (dividend/split-adjusted prices)
   - position.shift(1) -> the signal seen at today's close is only acted on
     starting tomorrow's return. No look-ahead bias.

 Run this in a single Google Colab cell.
================================================================================
"""

# ------------------------------------------------------------------
# 0. SETUP
# ------------------------------------------------------------------
!pip install yfinance --upgrade --quiet

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import warnings
warnings.filterwarnings("ignore")

TICKER      = "SPY"
START_DATE  = "1993-01-01"
INITIAL_CAP = 10000.0

# ---- Winning parameters (from the grid search) ----
IBS_ENTRY = 0.20   # buy when IBS < IBS_ENTRY
IBS_EXIT  = 0.80   # sell when IBS > IBS_EXIT


# ------------------------------------------------------------------
# 1. DATA INGESTION
# ------------------------------------------------------------------
print(f"Downloading {TICKER} data from {START_DATE} to present (auto_adjust=True)...")
raw = yf.download(TICKER, start=START_DATE, auto_adjust=True, progress=False)
if isinstance(raw.columns, pd.MultiIndex):
    raw.columns = raw.columns.get_level_values(0)

data = raw[["Open", "High", "Low", "Close", "Volume"]].dropna().copy()
print(f"Data loaded: {data.index[0].date()} -> {data.index[-1].date()}  "
      f"({len(data)} trading days)\n")


# ------------------------------------------------------------------
# 2. INDICATOR — IBS
# ------------------------------------------------------------------
rng = (data["High"] - data["Low"]).replace(0, np.nan)
data["IBS"] = ((data["Close"] - data["Low"]) / rng).fillna(0.5)
data["DailyReturn"] = data["Close"].pct_change()
data = data.dropna().copy()


# ------------------------------------------------------------------
# 3. BACKTEST — STATE MACHINE (no look-ahead bias)
# ------------------------------------------------------------------
n = len(data)
raw_signal = np.zeros(n, dtype=int)
in_trade = False
entry_arr = (data["IBS"] < IBS_ENTRY).values
exit_arr  = (data["IBS"] > IBS_EXIT).values

for i in range(n):
    if not in_trade:
        if entry_arr[i]:
            in_trade = True
    else:
        if exit_arr[i]:
            in_trade = False
    raw_signal[i] = 1 if in_trade else 0

raw_position = pd.Series(raw_signal, index=data.index)
position = raw_position.shift(1).fillna(0)        # <-- avoids look-ahead bias
strat_ret = position * data["DailyReturn"]
equity = (1 + strat_ret).cumprod()

# Buy & hold benchmark
bh_ret = data["DailyReturn"]
bh_equity = (1 + bh_ret).cumprod()


# ------------------------------------------------------------------
# 4. METRICS
# ------------------------------------------------------------------
def compute_metrics(df, position, strat_ret, equity):
    years = (df.index[-1] - df.index[0]).days / 365.25
    final_equity = equity.iloc[-1]
    cagr = (final_equity ** (1 / years) - 1) * 100 if final_equity > 0 else -100.0
    exposure = position.mean() * 100
    running_max = equity.cummax()
    drawdown = (equity - running_max) / running_max
    max_dd = drawdown.min() * 100
    ann_vol = strat_ret.std() * np.sqrt(252)
    sharpe = (strat_ret.mean() * 252) / ann_vol if ann_vol > 0 else 0.0

    trades = []
    in_trade_ = False
    trade_ret = 1.0
    pos_vals = position.values
    ret_vals = strat_ret.values
    for i in range(len(df)):
        if pos_vals[i] == 1:
            if not in_trade_:
                in_trade_ = True
                trade_ret = 1.0
            trade_ret *= (1 + ret_vals[i])
        else:
            if in_trade_:
                trades.append(trade_ret - 1)
                in_trade_ = False
    if in_trade_:
        trades.append(trade_ret - 1)
    trades = np.array(trades)

    n_trades = len(trades)
    if n_trades > 0:
        win_rate = (trades > 0).mean() * 100
        gross_profit = trades[trades > 0].sum()
        gross_loss = -trades[trades < 0].sum()
        profit_factor = gross_profit / gross_loss if gross_loss > 0 else np.inf
    else:
        win_rate = 0.0
        profit_factor = 0.0

    return {
        "CAGR (%)": cagr, "Exposure (%)": exposure, "MaxDD (%)": max_dd,
        "Sharpe": sharpe, "WinRate (%)": win_rate, "ProfitFactor": profit_factor,
        "NumTrades": n_trades, "FinalEquityMult": final_equity
    }, drawdown


strat_metrics, strat_dd = compute_metrics(data, position, strat_ret, equity)
bh_position = pd.Series(1, index=data.index)
bh_metrics, bh_dd = compute_metrics(data, bh_position, bh_ret, bh_equity)


# ------------------------------------------------------------------
# 5. PRINT RESULTS
# ------------------------------------------------------------------
print("=" * 70)
print(f" IBS MEAN REVERSION  (Entry: IBS<{IBS_ENTRY}  /  Exit: IBS>{IBS_EXIT})")
print("=" * 70)
for k in ["CAGR (%)", "Exposure (%)", "MaxDD (%)", "Sharpe", "WinRate (%)",
          "ProfitFactor", "NumTrades"]:
    v = strat_metrics[k]
    print(f"{k:>15}: {v:,.2f}" if isinstance(v, float) else f"{k:>15}: {v}")
print("-" * 70)
print(" SPY BUY & HOLD (benchmark)")
print("-" * 70)
for k in ["CAGR (%)", "Exposure (%)", "MaxDD (%)", "Sharpe", "WinRate (%)"]:
    v = bh_metrics[k]
    print(f"{k:>15}: {v:,.2f}" if isinstance(v, float) else f"{k:>15}: {v}")
print("=" * 70)

final_value_strat = INITIAL_CAP * equity.iloc[-1]
final_value_bh = INITIAL_CAP * bh_equity.iloc[-1]
print(f"\n${INITIAL_CAP:,.0f} invested in {data.index[0].date()} would now be worth:")
print(f"  Strategy   : ${final_value_strat:,.0f}")
print(f"  Buy & Hold : ${final_value_bh:,.0f}")


# ------------------------------------------------------------------
# 6. VISUALIZATION
# ------------------------------------------------------------------
fig, axes = plt.subplots(2, 1, figsize=(14, 10), sharex=True,
                          gridspec_kw={"height_ratios": [2.5, 1]})

ax1 = axes[0]
ax1.plot(data.index, equity * INITIAL_CAP,
          label=f"IBS Strategy (Entry<{IBS_ENTRY} / Exit>{IBS_EXIT})",
          color="#1f77b4", linewidth=1.3)
ax1.plot(data.index, bh_equity * INITIAL_CAP,
          label="SPY Buy & Hold", color="gray", linewidth=1.0, alpha=0.8)
ax1.set_yscale("log")
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x:,.0f}"))
ax1.set_title("Equity Curve (Log Scale) — IBS Mean Reversion vs SPY Buy & Hold",
              fontsize=12)
ax1.set_ylabel("Portfolio Value ($, log scale)")
ax1.legend(loc="upper left")
ax1.grid(True, which="both", alpha=0.3)

ax2 = axes[1]
ax2.fill_between(data.index, strat_dd * 100, 0, color="#d62728", alpha=0.5,
                  label="Strategy Drawdown")
ax2.plot(data.index, bh_dd * 100, color="gray", linewidth=0.8, alpha=0.7,
          label="SPY B&H Drawdown")
ax2.set_ylabel("Drawdown (%)")
ax2.set_xlabel("Date")
ax2.legend(loc="lower left")
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("ibs_winning_strategy.png", dpi=150)
plt.show()

"""
================================================================================
 SPY — IBS MEAN REVERSION: LIVE STATUS (TODAY ONWARD)
================================================================================
 Same strategy, same no-look-ahead-bias methodology as before, but the
 backtest window is restricted to START_DATE = 2026-07-28 (today) through
 whatever "today" is when you run this cell. Every future day you re-run
 it, it will include one more day of real data, effectively tracking the
 strategy's performance "from today onward" as time passes.

 NOTE ON DATA: IBS only needs each day's own High/Low/Close (no rolling
 lookback like a moving average), so starting exactly on the chosen date
 does NOT need any "warm-up" buffer of prior data -- day 1 already has a
 valid IBS reading.

 IMPORTANT: if you run this BEFORE the market has closed for START_DATE (or
 on a day before any bar exists yet for that date), the dataset will be
 empty. Run it after today's close, or the next trading day, for the first
 real reading.

 Colab still cannot run this unattended forever (session limits) -- see the
 automation notes printed at the end of the script.
================================================================================
"""

# ------------------------------------------------------------------
# 0. SETUP
# ------------------------------------------------------------------
!pip install yfinance --upgrade --quiet

import yfinance as yf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
from datetime import datetime
import warnings
warnings.filterwarnings("ignore")

TICKER      = "SPY"
START_DATE  = "2020-01-01"     # <-- restricted window starts TODAY, going forward
INITIAL_CAP = 10000.0
IBS_ENTRY   = 0.20
IBS_EXIT    = 0.80


# ------------------------------------------------------------------
# 1. DATA — always pulls from START_DATE up to the current date
# ------------------------------------------------------------------
today_str = datetime.now().strftime("%Y-%m-%d")
print(f"Downloading {TICKER} data from {START_DATE} through {today_str}...")
raw = yf.download(TICKER, start=START_DATE, auto_adjust=True, progress=False)
if isinstance(raw.columns, pd.MultiIndex):
    raw.columns = raw.columns.get_level_values(0)

data = raw[["Open", "High", "Low", "Close", "Volume"]].dropna().copy()

if len(data) == 0:
    raise SystemExit(f"No data returned for {TICKER} from {START_DATE}. "
                      f"Check ticker symbol / date / network access.")

print(f"Data loaded: {data.index[0].date()} -> {data.index[-1].date()}  "
      f"({len(data)} trading days)\n")


# ------------------------------------------------------------------
# 2. INDICATOR — IBS
# ------------------------------------------------------------------
rng = (data["High"] - data["Low"]).replace(0, np.nan)
data["IBS"] = ((data["Close"] - data["Low"]) / rng).fillna(0.5)
data["DailyReturn"] = data["Close"].pct_change().fillna(0)


# ------------------------------------------------------------------
# 3. BACKTEST (same state machine, no look-ahead bias)
# ------------------------------------------------------------------
n = len(data)
raw_signal = np.zeros(n, dtype=int)
in_trade = False
entry_arr = (data["IBS"] < IBS_ENTRY).values
exit_arr  = (data["IBS"] > IBS_EXIT).values
signal_change_idx = []

for i in range(n):
    prev_state = in_trade
    if not in_trade:
        if entry_arr[i]:
            in_trade = True
    else:
        if exit_arr[i]:
            in_trade = False
    if in_trade != prev_state:
        signal_change_idx.append(i)
    raw_signal[i] = 1 if in_trade else 0

raw_position = pd.Series(raw_signal, index=data.index)
position = raw_position.shift(1).fillna(0)          # executed next day
strat_ret = position * data["DailyReturn"]
equity = (1 + strat_ret).cumprod()

bh_ret = data["DailyReturn"]
bh_equity = (1 + bh_ret).cumprod()


# ------------------------------------------------------------------
# 4. METRICS
# ------------------------------------------------------------------
def compute_metrics(df, position, strat_ret, equity):
    days_span = (df.index[-1] - df.index[0]).days
    years = days_span / 365.25 if days_span > 0 else (1 / 365.25)
    final_equity = equity.iloc[-1]
    cagr = (final_equity ** (1 / years) - 1) * 100 if final_equity > 0 else -100.0
    exposure = position.mean() * 100
    running_max = equity.cummax()
    drawdown = (equity - running_max) / running_max
    max_dd = drawdown.min() * 100
    ann_vol = strat_ret.std() * np.sqrt(252)
    sharpe = (strat_ret.mean() * 252) / ann_vol if ann_vol > 0 else 0.0

    trades = []
    in_trade_ = False
    trade_ret = 1.0
    pos_vals = position.values
    ret_vals = strat_ret.values
    for i in range(len(df)):
        if pos_vals[i] == 1:
            if not in_trade_:
                in_trade_ = True
                trade_ret = 1.0
            trade_ret *= (1 + ret_vals[i])
        else:
            if in_trade_:
                trades.append(trade_ret - 1)
                in_trade_ = False
    if in_trade_:
        trades.append(trade_ret - 1)
    trades = np.array(trades)
    n_trades = len(trades)
    if n_trades > 0:
        win_rate = (trades > 0).mean() * 100
        gross_profit = trades[trades > 0].sum()
        gross_loss = -trades[trades < 0].sum()
        profit_factor = gross_profit / gross_loss if gross_loss > 0 else np.inf
    else:
        win_rate, profit_factor = 0.0, 0.0

    return {
        "CAGR (%)": cagr, "Exposure (%)": exposure, "MaxDD (%)": max_dd,
        "Sharpe": sharpe, "WinRate (%)": win_rate, "ProfitFactor": profit_factor,
        "NumTrades": n_trades, "FinalEquityMult": final_equity, "TotalReturn (%)": (final_equity - 1) * 100
    }, drawdown


strat_metrics, strat_dd = compute_metrics(data, position, strat_ret, equity)
bh_position = pd.Series(1, index=data.index)
bh_metrics, bh_dd = compute_metrics(data, bh_position, bh_ret, bh_equity)


# ------------------------------------------------------------------
# 5. PRINT RESULTS (note: CAGR is annualized off a partial-year window,
#    so treat it as illustrative, not a stable long-run figure — a few
#    months of data annualized swings a lot. TotalReturn (%) is the more
#    honest number for a short YTD window.)
# ------------------------------------------------------------------
print("=" * 70)
print(f" BACKTEST WINDOW: {data.index[0].date()} -> {data.index[-1].date()}")
print(f" IBS MEAN REVERSION  (Entry: IBS<{IBS_ENTRY}  /  Exit: IBS>{IBS_EXIT})")
print("=" * 70)
for k in ["TotalReturn (%)", "CAGR (%)", "Exposure (%)", "MaxDD (%)", "Sharpe",
          "WinRate (%)", "ProfitFactor", "NumTrades"]:
    v = strat_metrics[k]
    print(f"{k:>16}: {v:,.2f}" if isinstance(v, float) else f"{k:>16}: {v}")
print("-" * 70)
print(" SPY BUY & HOLD (same window, benchmark)")
print("-" * 70)
for k in ["TotalReturn (%)", "CAGR (%)", "MaxDD (%)", "Sharpe"]:
    v = bh_metrics[k]
    print(f"{k:>16}: {v:,.2f}")
print("=" * 70)
print("\n[Note] CAGR annualizes a partial-year window and can look extreme; "
      "TotalReturn (%) is the more reliable number for a YTD-style window.\n")


# ------------------------------------------------------------------
# 6. LIVE STATUS — "where are we RIGHT NOW"
# ------------------------------------------------------------------
last_date   = data.index[-1]
last_ibs    = data["IBS"].iloc[-1]
raw_state_today = raw_position.iloc[-1]
executed_position_today = position.iloc[-1]

days_since_change = None
if signal_change_idx:
    last_change_i = signal_change_idx[-1]
    days_since_change = (n - 1) - last_change_i

print("#" * 70)
print("#  LIVE STATUS")
print("#" * 70)
print(f" As of last close ({last_date.date()}):")
print(f"   Today's IBS reading        : {last_ibs:.3f}")
print(f"   Position HELD today        : {'LONG (in SPY)' if executed_position_today == 1 else 'FLAT (in cash)'}")
print(f"   Decision made at this close: {'STAY / GO LONG tomorrow' if raw_state_today == 1 else 'STAY / GO FLAT tomorrow'}")
if days_since_change is not None:
    print(f"   Days since last signal flip: {days_since_change}")
if raw_state_today == 1 and last_ibs > IBS_EXIT:
    print(f"   -> IBS ({last_ibs:.3f}) is ABOVE exit level ({IBS_EXIT}): expect EXIT next session.")
elif raw_state_today == 0 and last_ibs < IBS_ENTRY:
    print(f"   -> IBS ({last_ibs:.3f}) is BELOW entry level ({IBS_ENTRY}): expect ENTRY next session.")
else:
    print(f"   -> No new signal today. Holding current state.")
print("#" * 70)

final_value_strat = INITIAL_CAP * equity.iloc[-1]
final_value_bh = INITIAL_CAP * bh_equity.iloc[-1]
print(f"\n${INITIAL_CAP:,.0f} invested on {data.index[0].date()} would now be worth:")
print(f"  Strategy   : ${final_value_strat:,.0f}")
print(f"  Buy & Hold : ${final_value_bh:,.0f}")


# ------------------------------------------------------------------
# 7. CHARTS
# ------------------------------------------------------------------
fig, axes = plt.subplots(2, 1, figsize=(14, 10), sharex=True,
                          gridspec_kw={"height_ratios": [2.5, 1]})

ax1 = axes[0]
ax1.plot(data.index, equity * INITIAL_CAP,
          label=f"IBS Strategy (Entry<{IBS_ENTRY} / Exit>{IBS_EXIT})",
          color="#1f77b4", linewidth=1.3, marker="o", markersize=2)
ax1.plot(data.index, bh_equity * INITIAL_CAP,
          label="SPY Buy & Hold", color="gray", linewidth=1.0, alpha=0.8)
ax1.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f"${x:,.0f}"))
ax1.set_title(f"Equity Curve — {data.index[0].date()} through {last_date.date()}", fontsize=12)
ax1.set_ylabel("Portfolio Value ($)")
ax1.legend(loc="upper left")
ax1.grid(True, alpha=0.3)

ax2 = axes[1]
ax2.fill_between(data.index, strat_dd * 100, 0, color="#d62728", alpha=0.5,
                  label="Strategy Drawdown")
ax2.plot(data.index, bh_dd * 100, color="gray", linewidth=0.8, alpha=0.7,
          label="SPY B&H Drawdown")
ax2.set_ylabel("Drawdown (%)")
ax2.set_xlabel("Date")
ax2.legend(loc="lower left")
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("ibs_2026_ytd_status.png", dpi=150)
plt.show()

# ------------------------------------------------------------------
# 8. NOTE ON TRUE "ALWAYS ON" AUTOMATION
# ------------------------------------------------------------------
print("""
------------------------------------------------------------------------------
NOTE: Colab still cannot run this by itself every day, unattended.
For real hands-off daily checks, run this same script via:
  - GitHub Actions (free) on a cron schedule (e.g. weekdays after US close)
  - A cron job on any always-on machine/VM

Just re-run this cell manually any day and it will always show the window
from 2026-01-01 through whatever "today" is.
------------------------------------------------------------------------------
""")